import Image from "next/image";
import localFont from "next/font/local";
import Link from "next/link";
import { ArrowUpRight, Atom, BatteryCharging, Cpu, Factory, FlaskConical, Gauge, Microscope, Network, Orbit, ShieldCheck, Waves, Zap } from "lucide-react";
import UnicornBackground from "@/components/UnicornBackground";

const syne = localFont({
  src: "../../public/shodh-new/Syne/Syne-VariableFont_wght.ttf",
  display: "swap",
  weight: "100 900",
});

const dimensions = [
  {
    label: "Micro / Quantum",
    body: "Electron bonding and molecular affinities.",
    icon: Atom,
  },
  {
    label: "Meso / Fluids",
    body: "Viscosity and non-Newtonian rheology.",
    icon: Waves,
  },
  {
    label: "Macro / Factory",
    body: "Impeller shear, mixing time, and thermal dynamics in 10,000L vats.",
    icon: Factory,
  },
];

const visionCards = [
  {
    title: "Virtualizing Innovation",
    body: "Transitioning physical Design of Experiments (DoE) entirely in silico. We simulate 10,000 failures computationally so the wet-lab only tests the guaranteed winners.",
    icon: Cpu,
  },
  {
    title: "The Engine for Autonomous Factories",
    body: "Shodh AI is not just a chatbot. It is the core \"Physics Brain\" that future AI agents will use to autonomously monitor, control, and optimize chemical and biological factories worldwide.",
    icon: Network,
  },
  {
    title: "The Goal",
    body: "Moving India from a hub of contract execution to the global epicenter of high-value scientific IP and process intelligence.",
    icon: Orbit,
  },
];

const tractionCards = [
  {
    title: "Target Verticals",
    body: "Specialty Chemicals, Pharmaceuticals, Petrochemicals, and Battery Materials — all governed by the same underlying fluid and thermodynamic laws.",
    icon: BatteryCharging,
  },
  {
    title: "Commercial Proof",
    body: "We have already executed computational pilots with industry leaders like National Resilience (US), Axella Biotech (US), A123 (US), Aarti Industries (Chem), Jubilant Ingrevia, and Biosys (Chem and Bio CRO).",
    icon: ShieldCheck,
  },
  {
    title: "The Output",
    body: "For these partners, the model successfully synthesized novel molecular routes and predicted complex scale-up physics, validating our Sim-to-Real translation.",
    icon: Gauge,
  },
];

const products = [
  {
    eyebrow: "Shodh SYNTH / The Process",
    title: "Shodh SYNTH",
    body: "Beyond standard retrosynthesis. It uses first-principles thermodynamics to invent novel, cheaper catalytic routes that bypass existing patents and optimize lab yields.",
    icon: FlaskConical,
  },
  {
    eyebrow: "Shodh SCALE / The Factory",
    title: "Shodh SCALE",
    body: "The ultimate Bioreactor Digital Twin. Ingests bench-scale chemistry to predict thermal runaways and non-Newtonian fluid behaviors in massive Continuous Stirred-Tank Reactors (CSTRs).",
    icon: Factory,
  },
];

const smallMoleculeCards = [
  {
    title: "Zero-Shot Discovery",
    body: "We feed the model a target protein; it outputs highly potent hits.",
    icon: Microscope,
  },
  {
    title: "Automated Hit-to-Lead",
    body: "The model autonomously mutated scaffolds to avoid \"Molecular Obesity,\" balancing potency with ADMET safety (e.g., Caco-2, hERG, CYP450).",
    icon: Atom,
  },
  {
    title: "The Results",
    body: "Generated an 18,000-molecule proprietary IP catalog overnight. We successfully mapped sub-nanomolar, synthesizable hits for oncology (p53, KRAS) that are ready for wet-lab SPR validation today.",
    icon: FlaskConical,
  },
];

const modalityCards = [
  {
    title: "Lipid Nanoparticles (LNPs)",
    body: "We model the thermodynamic self-assembly and phys-chem stability of LNPs for mRNA and biologic delivery.",
    icon: Orbit,
  },
  {
    title: "Peptides & PROTACs",
    body: "Designing highly flexible, \"chameleonic\" structures that break Lipinski's rules but maintain cell permeability.",
    icon: Atom,
  },
  {
    title: "The Scale-Up of Living Cells",
    body: "Shodh SCALE directly addresses the Biomanufacturing bottleneck. We simulate the exact fluid shear-stress generated by impeller blades against the rupture limits of living mammalian cells—optimizing oxygen transfer without destroying the biological yield.",
    icon: Factory,
  },
];

export default function FoundationModelPage() {
  return (
    <main className={`${syne.className} relative min-h-screen bg-transparent text-[#1a1a2e] selection:bg-[#000042] selection:text-white`}>
      <UnicornBackground />

      <section className="relative z-10 min-h-screen overflow-hidden border-b border-[#000042]/20">
        <div className="relative mx-auto flex min-h-screen max-w-7xl flex-col px-5 py-6 sm:px-6 sm:py-8 md:px-10 lg:px-14">
          <header className="flex items-center justify-between py-2 sm:py-3">
            <Link href="/" className="flex items-center gap-3">
              <Image src="/shodh-new/White%20Shodh%20AI%20Brandmark.svg" alt="Shodh AI" width={40} height={40} priority className="h-8 w-8 invert sm:h-10 sm:w-10" />
            </Link>
            <Link
              href="/"
              className="inline-flex items-center gap-1.5 rounded-full border border-[#000042]/25 bg-transparent px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[0.04em] text-[#000042] transition hover:border-[#000042]/60 hover:bg-[#000042]/10 sm:px-5 sm:py-2 sm:text-[11px]"
            >
              Home
              <ArrowUpRight className="h-3 w-3 sm:h-3.5 sm:w-3.5" />
            </Link>
          </header>

          <div className="flex flex-1 items-center py-10 sm:py-16 lg:py-20">
            <h1 className="max-w-6xl text-[40px] font-medium leading-[1.02] tracking-[-0.05em] text-[#000042] sm:text-6xl md:text-7xl lg:text-8xl xl:text-[104px]">
              A Universal Foundation Model bridging Molecular Discovery and Industrial Scale-Up
            </h1>
          </div>
        </div>
      </section>

      <section className="relative z-10 min-h-screen border-y border-[#000042]/10 px-5 py-12 text-[#1a1a2e] sm:px-6 sm:py-20 md:px-10 lg:px-14">
        <div className="mx-auto flex min-h-[calc(100vh-6rem)] max-w-7xl flex-col justify-center">
          <div className="grid gap-8 lg:grid-cols-12 lg:items-end">
            <div className="lg:col-span-8">
              <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#000042]/50 sm:text-xs sm:tracking-[0.24em]">Micro to Macro</p>
              <h2 className="mt-3 text-4xl font-medium tracking-[-0.04em] text-[#000042] sm:mt-4 sm:text-5xl md:text-7xl">
                One continuous mathematical space for physical reasoning.
              </h2>
            </div>
            <div className="rounded-3xl border border-[#000042]/10 bg-white/30 p-6 shadow-2xl shadow-[#000042]/10 backdrop-blur-xl lg:col-span-4 lg:p-7">
              <p className="text-xs uppercase tracking-[0.2em] text-[#000042]/55">UNIPHY</p>
              <p className="mt-4 text-2xl font-light leading-tight tracking-[-0.04em] text-[#000042]">
                A 10-billion parameter foundation model that computes physics in a single latent space.
              </p>
            </div>
          </div>
          <div className="mt-10 grid gap-5 md:grid-cols-3 lg:mt-14">
            {dimensions.map((item) => {
              const Icon = item.icon;
              return (
                <div key={item.label} className="rounded-3xl border border-[#000042]/10 bg-white/30 p-6 shadow-xl shadow-[#000042]/5 backdrop-blur-md md:p-7">
                  <Icon className="h-8 w-8 text-[#000042]" />
                  <h3 className="mt-6 text-2xl font-semibold tracking-[-0.03em] text-[#000042]">{item.label}</h3>
                  <p className="mt-3 text-base leading-relaxed text-[rgba(0,0,66,0.75)]">{item.body}</p>
                </div>
              );
            })}
          </div>
          <p className="mt-8 max-w-4xl text-xl font-light leading-relaxed tracking-[-0.02em] text-[rgba(0,0,66,0.75)] md:text-2xl">
            The same model designs the molecule and the factory process simultaneously.
          </p>
        </div>
      </section>

      <section className="relative z-10 min-h-screen border-y border-[#000042]/10 px-5 py-12 text-[#1a1a2e] sm:px-6 sm:py-20 md:px-10 lg:px-14">
        <div className="mx-auto flex min-h-[calc(100vh-6rem)] max-w-7xl flex-col justify-center">
          <div className="max-w-4xl">
            <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#000042]/50 sm:text-xs sm:tracking-[0.24em]">Physical Manufacturing</p>
            <h2 className="mt-3 text-4xl font-medium tracking-[-0.04em] text-[#000042] sm:mt-4 sm:text-5xl md:text-7xl">
              What cloud computing did for software, UNIPHY does for factories.
            </h2>
          </div>
          <div className="mt-10 grid gap-5 md:grid-cols-3 lg:mt-14">
            {visionCards.map((card) => {
              const Icon = card.icon;
              return (
                <div key={card.title} className="rounded-3xl border border-[#000042]/10 bg-white/30 p-6 shadow-xl shadow-[#000042]/5 backdrop-blur-md md:p-7">
                  <Icon className="h-8 w-8 text-[#000042]" />
                  <h3 className="mt-6 text-2xl font-semibold tracking-[-0.03em] text-[#000042]">{card.title}</h3>
                  <p className="mt-3 text-base leading-relaxed text-[rgba(0,0,66,0.75)]">{card.body}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      <section className="relative z-10 min-h-screen border-y border-[#000042]/10 px-5 py-12 text-[#1a1a2e] sm:px-6 sm:py-20 md:px-10 lg:px-14">
        <div className="mx-auto flex min-h-[calc(100vh-6rem)] max-w-7xl flex-col justify-center">
          <div className="grid gap-8 lg:grid-cols-12 lg:items-end">
            <div className="lg:col-span-7">
              <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#000042]/50 sm:text-xs sm:tracking-[0.24em]">Current Sectors & Commercial Traction</p>
              <h2 className="mt-3 text-4xl font-medium tracking-[-0.04em] text-[#000042] sm:mt-4 sm:text-5xl md:text-7xl">
                Emergent properties proven across overlapping industries.
              </h2>
            </div>
            <div className="rounded-3xl bg-[#000042] p-6 text-white shadow-2xl shadow-[#000042]/15 lg:col-span-5 lg:p-8">
              <p className="text-xs uppercase tracking-[0.2em] text-white/55">Pilot partners</p>
              <p className="mt-4 text-3xl font-light leading-tight tracking-[-0.04em] md:text-4xl">
                National Resilience, Axella Biotech, A123, Aarti Industries, Jubilant Ingrevia, and Biosys.
              </p>
            </div>
          </div>
          <div className="mt-10 grid gap-5 md:grid-cols-3 lg:mt-14">
            {tractionCards.map((card) => {
              const Icon = card.icon;
              return (
                <div key={card.title} className="rounded-3xl border border-[#000042]/10 bg-white/30 p-6 shadow-xl shadow-[#000042]/5 backdrop-blur-md md:p-7">
                  <Icon className="h-8 w-8 text-[#000042]" />
                  <h3 className="mt-6 text-2xl font-semibold tracking-[-0.03em] text-[#000042]">{card.title}</h3>
                  <p className="mt-3 text-base leading-relaxed text-[rgba(0,0,66,0.75)]">{card.body}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      <section className="relative z-10 border-y border-[#000042]/10">
        {products.map((product, index) => {
          const Icon = product.icon;
          const panel = (
            <div className="flex min-h-[auto] flex-col justify-between gap-8 bg-white px-5 py-8 sm:px-6 sm:py-10 md:px-10 lg:min-h-[78vh] lg:px-[60px] lg:py-[60px]">
              <div className="max-w-xl text-[17px] font-normal leading-[1.5] tracking-[-0.01em] text-[#000042] md:text-[19px]">
                {product.body}
              </div>
              <div className="mt-2 max-w-full lg:mt-14">
                <p className="text-[10px] font-semibold uppercase tracking-[1.5px] text-[#000042] sm:text-[11px]">{product.eyebrow}</p>
                <h2 className="mt-4 max-w-full whitespace-normal text-[42px] font-semibold uppercase leading-[0.88] tracking-[-0.02em] text-[#000042] sm:mt-5 sm:text-[56px] lg:text-[72px]">
                  {product.title}
                </h2>
              </div>
            </div>
          );
          const visual = (
            <div className="flex min-h-[280px] items-center justify-center px-5 py-10 sm:min-h-[52vh] sm:px-6 md:px-10 lg:min-h-[78vh] lg:px-[60px] lg:py-[60px]">
              <div className="flex h-full min-h-[240px] w-full flex-col items-center justify-between text-[#000042] sm:min-h-[420px]">
                <span className="text-[10px] font-semibold uppercase tracking-[1.5px] text-[#000042]/75 sm:text-xs">
                  {index === 0 ? "Process Intelligence" : "Factory Intelligence"}
                </span>
                <div className="flex h-24 w-24 items-center justify-center rounded-[28px] border border-white/40 bg-white/25 text-[#000042] shadow-xl shadow-[#000042]/5 backdrop-blur-md sm:h-28 sm:w-28">
                  <Icon className="h-14 w-14 stroke-[1.5] sm:h-16 sm:w-16" />
                </div>
                <span className="text-[10px] font-semibold uppercase tracking-[1.5px] text-[#000042]/75 sm:text-xs">0{index + 1}</span>
              </div>
            </div>
          );

          return (
            <article key={product.title} className="grid min-h-[auto] grid-cols-1 lg:min-h-[78vh] lg:grid-cols-2">
              {index === 0 ? panel : visual}
              {index === 0 ? visual : panel}
            </article>
          );
        })}
      </section>

      <section className="relative z-10 min-h-screen border-y border-[#000042]/10 px-5 py-12 text-[#1a1a2e] sm:px-6 sm:py-20 md:px-10 lg:px-14">
        <div className="mx-auto flex min-h-[calc(100vh-6rem)] max-w-7xl flex-col justify-center">
          <div className="max-w-4xl">
            <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#000042]/50 sm:text-xs sm:tracking-[0.24em]">Biopharma / Small Molecules</p>
            <h2 className="mt-3 text-4xl font-medium tracking-[-0.04em] text-[#000042] sm:mt-4 sm:text-5xl md:text-7xl">
              We automate the entire hit-to-lead pipeline.
            </h2>
          </div>
          <div className="mt-10 grid gap-5 md:grid-cols-3 lg:mt-14">
            {smallMoleculeCards.map((card) => {
              const Icon = card.icon;
              return (
                <div key={card.title} className="rounded-3xl border border-[#000042]/10 bg-white/30 p-6 shadow-xl shadow-[#000042]/5 backdrop-blur-md md:p-7">
                  <Icon className="h-8 w-8 text-[#000042]" />
                  <h3 className="mt-6 text-2xl font-semibold tracking-[-0.03em] text-[#000042]">{card.title}</h3>
                  <p className="mt-3 text-base leading-relaxed text-[rgba(0,0,66,0.75)]">{card.body}</p>
                </div>
              );
            })}
          </div>
          <p className="mt-8 max-w-4xl text-xl font-light leading-relaxed tracking-[-0.02em] text-[rgba(0,0,66,0.75)] md:text-2xl">
            Target protein in, proprietary IP catalog out, ready for wet-lab validation.
          </p>
        </div>
      </section>

      <section className="relative z-10 mx-auto min-h-screen max-w-7xl px-5 py-12 sm:px-6 sm:py-20 md:px-10 lg:px-14">
        <div className="flex min-h-[calc(100vh-6rem)] items-center">
          <div className="w-full rounded-[1.5rem] border border-[#000042]/10 bg-white/30 p-6 shadow-2xl shadow-[#000042]/10 backdrop-blur-xl sm:rounded-[2rem] md:p-12 lg:p-14">
            <div className="grid gap-8 lg:grid-cols-12 lg:items-end">
              <div className="lg:col-span-8">
                <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#000042] sm:text-xs sm:tracking-[0.24em]">Advanced Modalities</p>
                <h2 className="mt-3 text-4xl font-medium tracking-[-0.04em] text-[#000042] sm:mt-4 sm:text-5xl md:text-7xl">
                  Advanced Modalities: Large Molecules & Biomanufacturing
                </h2>
              </div>
              <div className="lg:col-span-4">
                <div className="rounded-3xl bg-[#000042] p-5 text-white sm:p-6">
                  <p className="text-xs uppercase tracking-[0.2em] text-white/55">Biomanufacturing</p>
                  <p className="mt-3 text-2xl font-light leading-tight tracking-[-0.04em] sm:mt-4 sm:text-3xl">Optimize oxygen transfer without destroying biological yield.</p>
                </div>
              </div>
            </div>
            <div className="mt-10 grid gap-4 md:grid-cols-3">
              {modalityCards.map((card) => {
                const Icon = card.icon;
                return (
                  <div key={card.title} className="rounded-3xl border border-[#000042]/10 bg-white/35 p-5 shadow-xl shadow-[#000042]/5 backdrop-blur-md md:p-6">
                    <Icon className="h-7 w-7 text-[#000042]" />
                    <h3 className="mt-5 text-lg font-semibold tracking-[-0.03em] text-[#000042]">{card.title}</h3>
                    <p className="mt-3 text-sm leading-relaxed text-[rgba(0,0,66,0.75)]">{card.body}</p>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
