'use client';
import { useState } from 'react';
import { ArrowUpRight, RotateCcw } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent, Slider } from './primitives';

type Layer = 'flow' | 'oxygen' | 'stress';
function ReactorDrawing({ large, agitation, aeration, layer }: {large:boolean;agitation:number;aeration:number;layer:Layer}) {
 const left=large?184:218,right=large?416:382,spread=(right-left)/2-15;
 const color=layer==='oxygen'?'#96e7d2':layer==='stress'?'#ffb783':'#9eb6ff';
 return <svg className="reactor-diagram" viewBox="0 0 600 365" role="img" aria-label={`${large?'2,000 litre':'10 litre'} reactor. Illustrative ${layer} cross section, not CFD output.`}>
 <defs><pattern id="grid" width="25" height="25" patternUnits="userSpaceOnUse"><path d="M25 0L0 0 0 25" fill="none" stroke="#253246" strokeWidth=".7"/></pattern><marker id="arrow" markerWidth="7" markerHeight="7" refX="5" refY="3.5" orient="auto"><path d="M0 0L6 3.5L0 7" fill="none" stroke={color}/></marker><linearGradient id="liquid" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity=".02"/><stop offset="100%" stopColor={color} stopOpacity=".09"/></linearGradient></defs>
 <rect width="600" height="365" fill="url(#grid)"/>
 <path d={`M${left} 90Q300 44 ${right} 90V288Q300 337 ${left} 288Z`} fill="url(#liquid)" stroke="#8494af" strokeWidth="1.4"/><ellipse cx="300" cy="90" rx={(right-left)/2} ry="28" fill="none" stroke="#8494af" strokeWidth="1.2"/>
 <path d={`M${left} 126Q300 151 ${right} 126`} fill="none" stroke="#6a7d9f" strokeDasharray="4 5"/><path d={`M300 30V281M${left+16} 105V268M${right-16} 105V268`} fill="none" stroke="#65738c" strokeWidth="3"/>
 {[185,256].map(cy=><g key={cy}><path d={`M252 ${cy-9}L300 ${cy}L348 ${cy-9}V${cy+5}L300 ${cy+14}L252 ${cy+5}Z`} stroke="#c4cee0" fill="#233047"/><circle cx="300" cy={cy+2} r="5" fill="#cfdaef"/>{[-1,1].map(s=><path key={s} d={`M${300+s*40} ${cy}C${300+s*(spread+agitation*4)} ${cy-42} ${300+s*(spread+2)} ${cy-72} ${300+s*18} ${cy-67}C${300+s*5} ${cy-62} ${300+s*7} ${cy-24} ${300+s*20} ${cy-16}`} fill="none" stroke={color} strokeWidth={layer==='flow'?1.8:1} opacity={.45+agitation*.2} markerEnd="url(#arrow)"/>)}</g>)}
 {layer==='oxygen'&&Array.from({length:Math.round(aeration*16)},(_,i)=><circle key={i} cx={left+25+(i*53)%(right-left-50)} cy={143+(i*37)%132} r={2+i%3} fill="none" stroke={color} opacity={.35+i%3*.15}/>)}
 {layer==='stress'&&[185,256].map(y=><g key={y}>{[-1,1].map(s=><ellipse key={s} cx={300+s*48} cy={y} rx={9+agitation*7} ry={7+agitation*4} fill={color} opacity={.1+agitation*.05} stroke={color} strokeDasharray="3 3"/>)}</g>)}
 <path d="M300 310V332H446M350 186H449L467 168" fill="none" stroke="#697a97"/><text x="452" y="337" fill="#b5c3db" fontSize="12">gas inlet</text><text x="470" y="163" fill="#b5c3db" fontSize="12">impeller</text><path d={`M${left} 110H124L109 95`} fill="none" stroke="#697a97"/><text x="31" y="91" fill="#b5c3db" fontSize="12">vessel geometry</text><text x="25" y="337" fill="#8e9eb8" fontSize="12">CROSS SECTION / SCHEMATIC</text>
 </svg>;
}
function RangeControl({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}) {
 return <div className="range-control"><div><span>{label}</span><output>{value.toFixed(1)}<small> × reference</small></output></div><Slider aria-label={label} value={[value]} onValueChange={v=>onChange(Array.isArray(v)?v[0]:v)} min={.5} max={1.8} step={.1}/><div className="range-ends"><span>Lower</span><span>Higher</span></div></div>;
}
export function ScaleUpExplorer() {
 const [vessel,setVessel]=useState('2000'),[layer,setLayer]=useState<Layer>('flow'),[agitation,setAgitation]=useState(1),[aeration,setAeration]=useState(1);
 const metric=layer==='flow'?1/agitation:layer==='oxygen'?Math.pow(agitation,.65)*Math.pow(aeration,.4):Math.pow(agitation,1.5);
 const metricName=layer==='flow'?'Relative mixing time':layer==='oxygen'?'Relative oxygen-transfer index':'Relative stress index';
 const layerText=layer==='flow'?'Increasing agitation shortens the illustrative mixing time. Geometry changes require equipment-specific calibration.':layer==='oxygen'?'Agitation and aeration affect this illustrative transfer index. Actual oxygen availability also depends on cellular demand.':'The illustrative stress index rises with agitation. Stress alone does not predict cell rupture or viability.';
 return <section className="explorer wrap" id="explorer" aria-labelledby="explorer-title"><div className="section-top"><div><span className="chapter">01 / BIOREACTOR SCALE-UP</span><h2 id="explorer-title">Inside the scale-up problem</h2></div><span className="evidence-label">INTERACTIVE CONCEPT</span></div><div className="instrument"><div className="visual-panel"><div className="visual-top"><span><span className="signal-dot"/> BIOREACTOR / {vessel==='2000'?'PRODUCTION':'DEVELOPMENT'} SCALE</span><span>ILLUSTRATIVE</span></div><Tabs value={layer} onValueChange={v=>setLayer(v as Layer)} className="view-tabs"><TabsList><TabsTrigger value="flow">Mixing</TabsTrigger><TabsTrigger value="oxygen">Oxygen transport</TabsTrigger><TabsTrigger value="stress">Mechanical stress</TabsTrigger></TabsList>{(['flow','oxygen','stress'] as Layer[]).map(l=><TabsContent key={l} value={l}><ReactorDrawing large={vessel==='2000'} agitation={agitation} aeration={aeration} layer={l}/></TabsContent>)}</Tabs><div className="visual-bottom"><span>Geometry + process inputs → modeled response</span><span>{vessel==='2000'?'2,000':'10'} L</span></div></div><aside className="control-panel"><p className="eyebrow">CHANGE THE CONDITIONS</p><h3>One process.<br/>Different physical worlds.</h3><Tabs value={vessel} onValueChange={v=>setVessel(String(v))} className="vessel-tabs"><TabsList><TabsTrigger value="10">10 L vessel</TabsTrigger><TabsTrigger value="2000">2,000 L vessel</TabsTrigger></TabsList></Tabs><p className="vessel-note">Vessel size changes the illustration. Values show general relationships.</p><RangeControl label="Mixing intensity" value={agitation} onChange={setAgitation}/><RangeControl label="Airflow" value={aeration} onChange={setAeration}/><div className="model-output" aria-live="polite"><span>{metricName}</span><strong>{metric.toFixed(2)}<small>×</small></strong><p>{layerText}</p></div><button className="reset-button" onClick={()=>{setAgitation(1);setAeration(1);setVessel('2000');setLayer('flow')}}><RotateCcw size={14}/> Reset reference</button></aside></div><details className="model-note"><summary>How to read this explorer <ArrowUpRight size={14}/></summary><p>This is an educational model, not a live LUCAN simulation or validated operating recommendation. Values are dimensionless and normalized to a reference of 1. Vessel selection changes the schematic only; it does not calculate a scale-up factor. Mixing time = 1 / agitation; oxygen-transfer index = agitation^0.65 × aeration^0.4; stress index = agitation^1.5. These illustrative relationships demonstrate tradeoffs. They do not predict viability, actual kLa, or a safe operating envelope.</p></details><p className="always-note">Educational illustration · Actual process settings require validated simulations and measurements</p></section>;
}
