'use client';
import { useState } from 'react';
import { ArrowUpRight, ArrowRight, RotateCcw, Atom, Waves, Filter, Droplets } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent, Slider } from './primitives';

type Layer = 'flow' | 'oxygen' | 'stress';
function ReactorDrawing({ large, agitation, aeration, layer }: {large:boolean;agitation:number;aeration:number;layer:Layer}) {
 const left=large?184:218,right=large?416:382,spread=(right-left)/2-15;
 const color=layer==='oxygen'?'#96e7d2':layer==='stress'?'#ffb783':'#9eb6ff';
 return <svg className="reactor-diagram" viewBox="0 0 600 365" role="img" aria-label={`${large?'2,000 litre':'10 litre'} reactor. Illustrative ${layer} cross section, not CFD output.`}>
 <defs><pattern id="grid" width="25" height="25" patternUnits="userSpaceOnUse"><path d="M25 0L0 0 0 25" fill="none" stroke="#253246" strokeWidth=".7"/></pattern><marker id="arrow" markerWidth="7" markerHeight="7" refX="5" refY="3.5" orient="auto"><path d="M0 0L6 3.5L0 7" fill="none" stroke={color}/></marker><linearGradient id="liquid" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity=".02"/><stop offset="100%" stopColor={color} stopOpacity=".09"/></linearGradient></defs>
 <rect width="600" height="365" fill="url(#grid)"/>
 <path d={`M${left} 90Q300 44 ${right} 90V288Q300 337 ${left} 288Z`} fill="url(#liquid)" stroke="#8494af" strokeWidth="1.4"/><ellipse cx="300" cy="90" rx={(right-left)/2} ry="28" fill="none" stroke="#8494af" strokeWidth="1.2"/>
 <path d={`M${left} 126Q300 151 ${right} 126`} fill="none" stroke="#6a7d9f" strokeDasharray="4 5"/><path d={`M300 30V281M${left+16} 105V268M${right-16} 105V268`} fill="none" stroke="#65738c" strokeWidth="3"/>
 {[185,256].map(cy=><g key={cy}><path d={`M252 ${cy-9}L300 ${cy}L348 ${cy-9}V${cy+5}L300 ${cy+14}L252 ${cy+5}Z`} stroke="#c4cee0" fill="#233047"/><circle cx="300" cy={cy+2} r="5" fill="#cfdaef"/>{[-1,1].map(s=><path key={s} d={`M${300+s*40} ${cy}C${300+s*(spread+agitation*4)} ${cy-42} ${300+s*(spread+2)} ${cy-72} ${300+s*18} ${cy-67}C${300+s*5} ${cy-62} ${300+s*7} ${cy-24} ${300+s*20} ${cy-16}`} fill="none" stroke={color} strokeWidth={layer==='flow'?1.8:1} opacity={.45+agitation*.2} markerEnd="url(#arrow)"/>)}</g>)}
 {layer==='oxygen'&&Array.from({length:Math.round(aeration*16)},(_,i)=><circle key={i} cx={left+25+(i*53)%(right-left-50)} cy={143+(i*37)%132} r={2+i%3} fill="none" stroke={color} opacity={.35+i%3*.15}/>)}
 {layer==='stress'&&[185,256].map(y=><g key={y}>{[-1,1].map(s=><ellipse key={s} cx={300+s*48} cy={y} rx={9+agitation*7} ry={7+agitation*4} fill={color} opacity={.1+agitation*.05} stroke={color} strokeDasharray="3 3"/>)}</g>)}
 <path d="M300 310V332H446M350 186H449L467 168" fill="none" stroke="#697a97"/><text x="452" y="337" fill="#b5c3db" fontSize="12">gas inlet</text><text x="470" y="163" fill="#b5c3db" fontSize="12">impeller</text><path d={`M${left} 110H124L109 95`} fill="none" stroke="#697a97"/><text x="31" y="91" fill="#b5c3db" fontSize="12">vessel geometry</text><text x="25" y="337" fill="#8e9eb8" fontSize="12">CROSS SECTION / SCHEMATIC</text>
 </svg>;
}
function RangeControl({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}) {
 return <div className="range-control"><div><span>{label}</span><output>{value.toFixed(1)}<small> × reference</small></output></div><Slider aria-label={label} value={[value]} onValueChange={v=>onChange(Array.isArray(v)?v[0]:v)} min={.5} max={1.8} step={.1}/><div className="range-ends"><span>Lower</span><span>Higher</span></div></div>;
}
const domains = [
 {id:'molecule',stage:'DISCOVERY',name:'Molecular simulation',icon:Atom,title:'Understand the molecule before scaling the process.',description:'Simulate how antibody candidates move and interact in their surrounding fluid. Compare molecular behavior to prioritize candidates for the next round of experiments.',inputs:['Protein structure','Molecular interaction properties','Surrounding fluid conditions'],outputs:['Changes in protein shape','Molecular interactions','Candidate comparisons'],equation:'Molecular structure + environment → predicted behavior',limit:'Binding rates require dedicated sampling and experimental calibration. Candidate performance and manufacturability must be measured.'},
 {id:'reactor',stage:'PRODUCTION',name:'Bioreactor scale-up',icon:Waves,title:'Calculate the conditions for manufacturing scale.',description:'A larger tank changes how fluid mixes, oxygen moves and cells experience mechanical stress. UNIPHY models those conditions and searches for equipment settings that meet the process requirements.',inputs:['Reactor geometry','Mixing speed and airflow','Fluid properties and cell demand'],outputs:['Mixing behavior','Oxygen transport','Mechanical stress from flow'],equation:'Equipment + process requirements → candidate operating settings',limit:'Predictions require calibration for the equipment and process. Cell viability depends on biological factors as well as the fluid environment.'},
 {id:'purification',stage:'SEPARATION',name:'Purification',icon:Filter,title:'Recover the protein. Understand the separation.',description:'After production, the protein must be separated from the surrounding mixture. Model liquid flow and protein binding in purification equipment to evaluate pressure, loading and throughput.',inputs:['Column or membrane geometry','Separation material properties','Feed composition and flow'],outputs:['Pressure distribution','Protein binding profiles','Flow through the membrane'],equation:'Separation equipment + feed conditions → predicted recovery behavior',limit:'Chromatography captures and releases antibodies; membranes used for concentration retain them. Recovery and fouling require validation for each operation.'},
 {id:'formulation',stage:'DELIVERY',name:'Formulation and delivery',icon:Droplets,title:'Predict how the medicine flows.',description:'Concentrated protein medicines can become difficult to pump, fill or inject. Connect measured liquid properties with equipment geometry to calculate flow resistance and pressure requirements.',inputs:['Measured liquid flow properties','Filling or injection device','Flow rate and temperature'],outputs:['Viscosity during flow','Pressure requirements','Changes in local flow speed'],equation:'Liquid properties + device geometry → delivery flow',limit:'Liquid flow, aggregation, shelf stability and sterility are different properties. Each requires its own testing.'},
];
function Platform(){return <section className="wrap platform-section" id="pipeline"><div className="section-top"><div><span className="chapter">02 / THE PLATFORM</span><h2>Physics across the process.</h2></div><p>From the first molecule to the final dose.<br/>See where physics changes the engineering decisions.</p></div><Tabs defaultValue="reactor" className="platform-tabs"><TabsList>{domains.map(d=><TabsTrigger value={d.id} key={d.id}><d.icon size={20}/><span><small>{d.stage}</small>{d.name}</span><ArrowRight size={16} className="tab-arrow"/></TabsTrigger>)}</TabsList>{domains.map(d=><TabsContent key={d.id} value={d.id}><div className="domain-content"><div className="domain-story"><span className="domain-stage">{d.stage}</span><h3>{d.title}</h3><p>{d.description}</p><div className="concept-equation">{d.equation}</div></div><div className="domain-io"><div><span className="eyebrow">INPUTS</span>{d.inputs.map((x,i)=><p key={x}><span>0{i+1}</span>{x}</p>)}</div><ArrowRight className="io-arrow" size={22}/><div><span className="eyebrow">MODEL OUTPUTS</span>{d.outputs.map((x,i)=><p key={x}><span>0{i+1}</span>{x}</p>)}</div></div></div><p className="domain-limit"><span>MODEL SCOPE</span>{d.limit}</p></TabsContent>)}</Tabs></section>}
const transferSteps=[
 {id:'specification',label:'01  Define the process',title:'Keep the requirements explicit.',text:'Define what the process needs: liquid properties, cellular oxygen demand and acceptable operating limits. UNIPHY records these requirements separately from the equipment model.',leftTitle:'Process specification',left:['Material properties','Oxygen demand','Defined process limits'],rightTitle:'Reference equipment',right:['Vessel geometry','Impeller and gas delivery','Equipment constraints'],out:'A defined process and reference equipment model'},
 {id:'geometry',label:'02  Change the equipment',title:'Replace the geometry. Retain the context.',text:'Add the receiving facility’s equipment geometry, mixing configuration and operating limits. Carry the process requirements forward, then recalculate how the new equipment changes the physical conditions.',leftTitle:'Process specification',left:['Material properties retained','Oxygen demand retained','Process limits reviewed'],rightTitle:'Receiving equipment',right:['New vessel geometry','New mixing configuration','New equipment limits'],out:'A process model matched to the new equipment'},
 {id:'solve',label:'03  Recalculate conditions',title:'Find a solution for the receiving reactor.',text:'Calculate mixing, oxygen transport and mechanical stress in the new reactor. Search for operating settings that meet the process requirements, then verify the predictions with physical measurements.',leftTitle:'Process requirements',left:['Defined objectives','Oxygen constraints','Measured stress limits'],rightTitle:'Equipment-specific solution',right:['Candidate operating settings','Predicted mixing, oxygen and stress','Assumptions and margins'],out:'Candidate settings for physical verification'},
];
function Transfer(){return <section className="transfer-section" id="transfer"><div className="wrap"><div className="transfer-heading"><div><span className="chapter">03 / PROCESS TRANSFER</span><h2>Carry the process.<br/>Recalculate for the equipment.</h2></div><p>Moving production to a new facility changes the equipment. UNIPHY carries the process requirements forward and recalculates the operating conditions for the receiving reactor.</p></div><Tabs defaultValue="specification" className="transfer-tabs"><TabsList>{transferSteps.map(s=><TabsTrigger value={s.id} key={s.id}>{s.label}</TabsTrigger>)}</TabsList>{transferSteps.map(s=><TabsContent value={s.id} key={s.id}><div className="transfer-diagram" aria-label="How process requirements and equipment models connect"><div className="transfer-node"><span className="node-kind">PROCESS</span><strong>{s.leftTitle}</strong>{s.left.map(x=><p key={x}>{x}</p>)}</div><div className="interface-node"><span className="connector-line"/><strong>UNIPHY</strong><span className="connector-line"/></div><div className={`transfer-node ${s.id!=='specification'?'changed':''}`}><span className="node-kind">{s.id==='solve'?'OUTPUT':'EQUIPMENT'}</span><strong>{s.rightTitle}</strong>{s.right.map(x=><p key={x}>{x}</p>)}</div></div><div className="transfer-explanation"><div><h3>{s.title}</h3><p>{s.text}</p></div><div className="step-result"><span className="eyebrow">THIS STEP PRODUCES</span><p>{s.out}</p></div></div></TabsContent>)}</Tabs><p className="transfer-caveat">This walkthrough illustrates process transfer. Facility qualification, analytical methods and manufacturing validation are also required before production.</p></div></section>}
function Evidence(){return <section className="wrap evidence-section" id="evidence"><div className="evidence-intro"><span className="chapter">04 / THE TECHNICAL BASIS</span><h2>Prediction earns trust<br/>through validation.</h2><p>The engineering goal is faster scale-up with fewer costly iterations. Demonstrating that value means testing computational speed, prediction accuracy and manufacturing performance.</p><a className="download-button" href="/research/UNIPHY_Biomanufacturing_Whitepaper.pdf" target="_blank" rel="noreferrer">Read the two-page whitepaper <ArrowUpRight size={18}/></a></div><div className="evidence-records"><article><span>01 / REPORTED PERFORMANCE</span><h3>10,000 scenarios in hours</h3><p>Company-reported internal simulations. Hardware, model fidelity and benchmark definitions are needed to establish a reproducible comparison. This is not a measured reduction in complete manufacturing time.</p></article><article><span>02 / PREDICTION ACCURACY</span><h3>Defined limits. Measured accuracy.</h3><p>Every prediction depends on its inputs and assumptions. Comparisons with physical measurements establish where a model is accurate, how large its errors are and which operating conditions it can assess.</p></article><details className="source-details"><summary>Technical references <ArrowUpRight size={14}/></summary><a href="https://pubmed.ncbi.nlm.nih.gov/38582408/" target="_blank" rel="noreferrer">CFD validation for large-scale cell culture <ArrowUpRight size={14}/></a><a href="https://stanford.edu/~boyd/cvxbook/" target="_blank" rel="noreferrer">Boyd & Vandenberghe · Convex Optimization <ArrowUpRight size={14}/></a><a href="https://www.who.int/publications/m/item/trs1044-annex4" target="_blank" rel="noreferrer">WHO · Technology transfer in pharmaceutical manufacturing <ArrowUpRight size={14}/></a><a href="https://cgmartini.nl/docs/faq/" target="_blank" rel="noreferrer">Martini · Model assumptions and limitations <ArrowUpRight size={14}/></a></details></div></section>}
export default function UniphyPage() {
 const [vessel,setVessel]=useState('2000'),[layer,setLayer]=useState<Layer>('flow'),[agitation,setAgitation]=useState(1),[aeration,setAeration]=useState(1);
 const metric=layer==='flow'?1/agitation:layer==='oxygen'?Math.pow(agitation,.65)*Math.pow(aeration,.4):Math.pow(agitation,1.5);
 const metricName=layer==='flow'?'Relative mixing time':layer==='oxygen'?'Relative oxygen-transfer index':'Relative stress index';
 const layerText=layer==='flow'?'Increasing agitation shortens the illustrative mixing time. Geometry changes require equipment-specific calibration.':layer==='oxygen'?'Agitation and aeration affect this illustrative transfer index. Actual oxygen availability also depends on cellular demand.':'The illustrative stress index rises with agitation. Stress alone does not predict cell rupture or viability.';
 return <><a className="skip-link" href="#explorer">Skip to reactor explorer</a><header className="site-header"><a href="#" className="wordmark" aria-label="UNIPHY home">UNI<span>PHY</span><i/></a><nav aria-label="Main navigation"><a href="#explorer">Scale-up explorer</a><a href="#pipeline">The platform</a><a href="#transfer">Process transfer</a></nav><a className="paper-link" href="/research/UNIPHY_Biomanufacturing_Whitepaper.pdf" target="_blank" rel="noreferrer">Whitepaper <ArrowUpRight size={16}/></a></header>
 <main><section className="intro wrap"><div><p className="eyebrow"><span/> A PHYSICAL FOUNDATION MODEL</p><h1>The physics of<br/><span>manufacturing scale.</span></h1></div><p className="intro-copy">Biomanufacturing uses living cells to make medicines. UNIPHY models the physics from molecule to factory, calculating how equipment and operating conditions shape the process.</p></section>
 <section className="explorer wrap" id="explorer" aria-labelledby="explorer-title"><div className="section-top"><div><span className="chapter">01 / BIOREACTOR SCALE-UP</span><h2 id="explorer-title">Inside the scale-up problem</h2></div><span className="evidence-label">INTERACTIVE CONCEPT</span></div><div className="instrument"><div className="visual-panel"><div className="visual-top"><span><span className="signal-dot"/> BIOREACTOR / {vessel==='2000'?'PRODUCTION':'DEVELOPMENT'} SCALE</span><span>ILLUSTRATIVE</span></div><Tabs value={layer} onValueChange={v=>setLayer(v as Layer)} className="view-tabs"><TabsList><TabsTrigger value="flow">Mixing</TabsTrigger><TabsTrigger value="oxygen">Oxygen transport</TabsTrigger><TabsTrigger value="stress">Mechanical stress</TabsTrigger></TabsList>{(['flow','oxygen','stress'] as Layer[]).map(l=><TabsContent key={l} value={l}><ReactorDrawing large={vessel==='2000'} agitation={agitation} aeration={aeration} layer={l}/></TabsContent>)}</Tabs><div className="visual-bottom"><span>Geometry + process inputs → modeled response</span><span>{vessel==='2000'?'2,000':'10'} L</span></div></div><aside className="control-panel"><p className="eyebrow">CHANGE THE CONDITIONS</p><h3>One process.<br/>Different physical worlds.</h3><Tabs value={vessel} onValueChange={v=>setVessel(String(v))} className="vessel-tabs"><TabsList><TabsTrigger value="10">10 L vessel</TabsTrigger><TabsTrigger value="2000">2,000 L vessel</TabsTrigger></TabsList></Tabs><p className="vessel-note">Vessel size changes the illustration. Values show general relationships.</p><RangeControl label="Mixing intensity" value={agitation} onChange={setAgitation}/><RangeControl label="Airflow" value={aeration} onChange={setAeration}/><div className="model-output" aria-live="polite"><span>{metricName}</span><strong>{metric.toFixed(2)}<small>×</small></strong><p>{layerText}</p></div><button className="reset-button" onClick={()=>{setAgitation(1);setAeration(1);setVessel('2000');setLayer('flow')}}><RotateCcw size={14}/> Reset reference</button></aside></div><details className="model-note"><summary>How to read this explorer <ArrowUpRight size={14}/></summary><p>This is an educational model, not a live UNIPHY simulation or validated operating recommendation. Values are dimensionless and normalized to a reference of 1. Vessel selection changes the schematic only; it does not calculate a scale-up factor. Mixing time = 1 / agitation; oxygen-transfer index = agitation^0.65 × aeration^0.4; stress index = agitation^1.5. These illustrative relationships demonstrate tradeoffs. They do not predict viability, actual kLa, or a safe operating envelope.</p></details><p className="always-note">Educational illustration · Actual process settings require validated simulations and measurements</p></section>
 <Platform/><Transfer/><Evidence/>
 <footer className="wrap"><span className="wordmark">UNIPHY</span><span>Physics for biomanufacturing.</span><a href="/research/UNIPHY_Biomanufacturing_Whitepaper.pdf" target="_blank" rel="noreferrer">Read the whitepaper <ArrowUpRight size={16}/></a></footer></main></>;
}
